#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-macholib
Version  : 1.16
Release  : 6
URL      : https://files.pythonhosted.org/packages/16/1b/85fd523a1d5507e9a5b63e25365e0a26410d5b6ee89082426e6ffff30792/macholib-1.16.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/1b/85fd523a1d5507e9a5b63e25365e0a26410d5b6ee89082426e6ffff30792/macholib-1.16.tar.gz
Summary  : Mach-O header analysis and editing
Group    : Development/Tools
License  : MIT
Requires: pypi-macholib-bin = %{version}-%{release}
Requires: pypi-macholib-license = %{version}-%{release}
Requires: pypi-macholib-python = %{version}-%{release}
Requires: pypi-macholib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(altgraph)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
macholib can be used to analyze and edit Mach-O headers, the executable
format used by Mac OS X.

%package bin
Summary: bin components for the pypi-macholib package.
Group: Binaries
Requires: pypi-macholib-license = %{version}-%{release}

%description bin
bin components for the pypi-macholib package.


%package license
Summary: license components for the pypi-macholib package.
Group: Default

%description license
license components for the pypi-macholib package.


%package python
Summary: python components for the pypi-macholib package.
Group: Default
Requires: pypi-macholib-python3 = %{version}-%{release}

%description python
python components for the pypi-macholib package.


%package python3
Summary: python3 components for the pypi-macholib package.
Group: Default
Requires: python3-core
Provides: pypi(macholib)
Requires: pypi(altgraph)

%description python3
python3 components for the pypi-macholib package.


%prep
%setup -q -n macholib-1.16
cd %{_builddir}/macholib-1.16
pushd ..
cp -a macholib-1.16 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656394932
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-macholib
cp %{_builddir}/macholib-1.16/LICENSE %{buildroot}/usr/share/package-licenses/pypi-macholib/52ec3df24c20fcd417b4d29819bea85b454ffcf8
cp %{_builddir}/macholib-1.16/doc/license.rst %{buildroot}/usr/share/package-licenses/pypi-macholib/f7c8530285650877d9b3d44075329c6dbf5de742
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/macho_dump
/usr/bin/macho_find
/usr/bin/macho_standalone

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-macholib/52ec3df24c20fcd417b4d29819bea85b454ffcf8
/usr/share/package-licenses/pypi-macholib/f7c8530285650877d9b3d44075329c6dbf5de742

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
