#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-macholib
Version  : 1.16
Release  : 1
URL      : https://files.pythonhosted.org/packages/16/1b/85fd523a1d5507e9a5b63e25365e0a26410d5b6ee89082426e6ffff30792/macholib-1.16.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/1b/85fd523a1d5507e9a5b63e25365e0a26410d5b6ee89082426e6ffff30792/macholib-1.16.tar.gz
Summary  : Mach-O header analysis and editing
Group    : Development/Tools
License  : MIT
Requires: pypi-macholib-bin = %{version}-%{release}
Requires: pypi-macholib-python = %{version}-%{release}
Requires: pypi-macholib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(altgraph)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
macholib can be used to analyze and edit Mach-O headers, the executable
format used by Mac OS X.

%package bin
Summary: bin components for the pypi-macholib package.
Group: Binaries

%description bin
bin components for the pypi-macholib package.


%package python
Summary: python components for the pypi-macholib package.
Group: Default
Requires: pypi-macholib-python3 = %{version}-%{release}

%description python
python components for the pypi-macholib package.


%package python3
Summary: python3 components for the pypi-macholib package.
Group: Default
Requires: python3-core
Provides: pypi(macholib)
Requires: pypi(altgraph)

%description python3
python3 components for the pypi-macholib package.


%prep
%setup -q -n macholib-1.16
cd %{_builddir}/macholib-1.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652688121
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/macho_dump
/usr/bin/macho_find
/usr/bin/macho_standalone

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
